CREATE TABLE review_likes (
  id VARCHAR(36) PRIMARY KEY,
  review_id VARCHAR(36) NOT NULL REFERENCES REVIEWS (id) ON DELETE CASCADE,
  user_id VARCHAR(36) NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  created_at TIMESTAMP DEFAULT NOW ()
)
